version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  jest_test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: cp .env.test .env
      - run: npm run lint
      - run: npm test
      - store_test_results:
          path: ~/repo/junit.xml

  detox_test:
    # Note: This flow has serious room for time improvment via caching
    macos:
      xcode: "9.0"
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: cp .env.test .env

      # Get everything we need to run detox
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: npm install -g react-native-cli
      - run: npm install -g detox-cli

      # fix: Error: `fsevents` unavailable
      # https://github.com/expo/expo/issues/854
      - run: npm r -g watchman
      - run: brew install watchman
      - run: npm run test:test-e2e

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - jest_test:
          requires:
            - build

# temporarily disable e2e tests while the brew formula for python in watchman fixes itself
#      - detox_test:
#         requires:
#            - build
#            - jest_test
#          filters:
#           branches:
#             only:
#               - develop
#               - master
